In [1]:
import numpy as np

In [2]:
from utils import *

In [3]:
grid_size = 5
wind = 0.1
discount = 0.9
horizon = 10
start_state = 15
feature_dim = 2
p1 = 0  # position of culvers burger joint
p2 = 24 # position of charging station

theta = 5*np.ones((2,1))


gw = BlockingGridworld(grid_size,wind,discount,horizon,start_state, feature_dim, p1,p2,theta)

In [11]:
Pa1 = gw.transition_probability[:,0,:]
Pa2 = gw.transition_probability[:,1,:]
Pa3 = gw.transition_probability[:,2,:]
Pa4 = gw.transition_probability[:,3,:]

P = [Pa1,Pa2,Pa3,Pa4]

In [53]:
Reach = {}

T = 7

# reach at time zero
Reach[str(0)] = [gw.start_state]

for t in range(1,T):
    
    pre = Reach[str(t-1)]
  
    pre_vec = np.zeros((1,gw.n_states))
    
    # create the vector of pre states 
    for s in pre:
        pre_vec[0][s] = 1.0
    
    # normalize
    pre_vec = pre_vec/pre_vec.sum()
    
    post_state = []
    
    for pre_state in pre:
        for Pa in P:
            transfer = pre_vec@Pa
            
            for index in np.argwhere(transfer> 0.0):
                post_state.append(index[1])
                
    post_state = list(set(post_state))
    Reach[str(t)] = post_state

In [55]:
Reach

{'0': [15],
 '1': [16, 10, 20, 15],
 '2': [5, 10, 11, 15, 16, 17, 20, 21],
 '3': [0, 5, 6, 10, 11, 12, 15, 16, 17, 18, 20, 21, 22],
 '4': [0, 1, 5, 6, 7, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23],
 '5': [0,
  1,
  5,
  6,
  7,
  8,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24],
 '6': [0,
  1,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24]}

In [59]:
np.sort(list(set(np.arange(1,25)) - set(pre) ))

array([2, 3, 4, 9])

In [63]:
Pa1

array([[0.05      , 0.925     , 0.        , 0.        , 0.        ,
        0.025     , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.

In [64]:
np.delete(Pa1, obj= [0,1], axis = 0)

array([[0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.

In [67]:
Reach["4"]

[0, 1, 5, 6, 7, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23]

In [71]:
Pa1 = np.delete(Pa1,0,0)

In [72]:
Pa1

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.